### ISSUE TITLE
data disappeared

### ISSUE THREAD

**Issue by iamxujian** [AzurLaneTools/AzurLaneData#1] opened 2022-05-20 11:57 UTC
data in some files disappeared. such as:

[buffCfg.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/CN/buffCfg.json)
[skillCfg.json](https://github.com/AzurLaneTools/AzurLaneData/blob/main/CN/skillCfg.json)

did some error occurred during converting lua to json?

**Comment by AutumnSun1996** [comment] 2022-05-20 12:03
It's caused by https://github.com/K0lb3/UnityPy/issues/112

Original issue is already solved, and the data should come back soon

**Comment by iamxujian** [comment] 2022-05-21 05:05
UnityPy, seems like a powerful lib, interesting. luckily to know a new lib. 
i'm expecting data's recurrence. Thank you very much.

**Comment by iamxujian** [comment] 2022-06-05 04:41
the data files are still empty, so i re-opened this one

**Comment by AutumnSun1996** [comment] 2022-06-15 13:39
Another issue comes from the lua code change.
Fixed in aba8350082297c99a574a0333b6caec744db79ad ~ 12c042ff79bd0dd402d24e381be98c9afe80e45c

**Closed as completed by AutumnSun1996** 2022-06-15 13:39 UTC
